SOURCES = \
		main.c \
		parsing/parsing_main.c \
		parsing/parsing_elem.c \
		parsing/parsing_grammar.c \
		parsing/parsing_token.c \
		parsing/parsing_error.c \
		parsing/parsing_lexer.c \
		parsing/parsing_split_1.c \
		parsing/parsing_split_2.c \
		history/history.c \
		env/env.c \
		env/env_edit.c \
		env/env_free.c \
		exec/exec.c \
		exec/prepare_cmds.c \
		exec/exec_cmd_path.c \
		flux/flux_append.c \
		flux/flux_heredoc.c \
		flux/flux_pipe.c \
		flux/flux_redir_input.c \
		flux/flux_redir_output.c \
		builtins/builtin_echo.c \
		builtins/builtin_cd.c \
		builtins/builtin_env.c \
		builtins/builtin_exit.c \
		builtins/builtin_export.c \
		builtins/builtin_pwd.c \
		builtins/builtin_unset.c \
		utils/utils_1.c \
		utils/utils_2.c \
		utils/utils_3.c \
		utils/utils_4.c \
		utils/utils_5.c \
		utils/utils_chr.c \
		debug/debug.c