SOURCES = \
		main.c \
		parsing/parsing_main.c \
		parsing/parsing_alloc.c \
		parsing/parsing_add.c \
		parsing/parsing_grammar.c \
		parsing/parsing_token.c \
		parsing/parsing_error.c \
		parsing/parsing_lexer.c \
		parsing/parsing_cleanup.c \
		parsing/parsing_split_1.c \
		parsing/parsing_split_2.c \
		parsing/parsing_split_3.c \
		env/env.c \
		env/env_edit.c \
		env/env_free.c \
		env/env_getter.c \
		env/env_exec.c \
		exec/exec.c \
		exec/prepare_cmds.c \
		exec/exec_cmd_path.c \
		heredoc/heredoc.c \
		builtins/builtin_echo.c \
		builtins/builtin_cd.c \
		builtins/builtin_env.c \
		builtins/builtin_exit.c \
		builtins/builtin_export.c \
		builtins/builtin_pwd.c \
		builtins/builtin_unset.c \
		utils/utils_1.c \
		utils/utils_2.c \
		libft/ft_isalnum.c \
		libft/ft_isalpha.c \
		libft/ft_isdigit.c \
		libft/ft_split.c \
		libft/ft_strchr.c \
		libft/ft_strcmp.c \
		libft/ft_strdup.c \
		libft/ft_strjoin.c \
		libft/ft_strlcpy.c \
		libft/ft_strlen.c \
		libft/ft_strnstr.c \
		libft/ft_strtrim.c \
		debug/debug.c
