SOURCES = \
		main.c \
		parsing/parsing_main.c \
		parsing/parsing_alloc.c \
		parsing/parsing_add.c \
		parsing/parsing_token.c \
		parsing/parsing_counta.c \
		parsing/parsing_countw.c \
		parsing/parsing_env.c \
		parsing/parsing_get.c \
		parsing/parsing_init.c \
		parsing/parsing_quotes.c \
		redir/redir_main.c \
		redir/redir_less.c \
		redir/redir_dless.c \
		redir/redir_great.c \
		redir/redir_dgreat.c \
		redir/redir_ret.c \
		redir/redir_get.c \
		env/env_main.c \
		env/env_edit.c \
		env/env_free.c \
		env/env_getter.c \
		env/env_exec.c \
		exec/exec.c \
		exec/prepare_cmds.c \
		exec/exec_cmd_path.c \
		exec/pipes.c \
		exec/pipeline.c \
		exec/redirection.c \
		exec/init_fds.c \
		heredoc/heredoc.c \
		signals/signals.c \
		builtins/builtin_echo.c \
		builtins/builtin_cd.c \
		builtins/builtin_env.c \
		builtins/builtin_exit.c \
		builtins/builtin_export.c \
		builtins/builtin_pwd.c \
		builtins/builtin_unset.c \
		builtins/select_builtin.c \
		utils/utils_1.c \
		utils/utils_2.c \
		libft/ft_isalnum.c \
		libft/ft_isalpha.c \
		libft/ft_isdigit.c \
		libft/ft_split.c \
		libft/ft_strchr.c \
		libft/ft_strcmp.c \
		libft/ft_strdup.c \
		libft/ft_strjoin.c \
		libft/ft_strlcpy.c \
		libft/ft_strlen.c \
		libft/ft_strnstr.c \
		libft/ft_strtrim.c \
		libft/ft_strncmp.c \
		libft/ft_substr.c \
		libft/ft_atoi.c \
		libft/ft_itoa.c \
		libft/ft_isnbr.c \
		debug/debug.c
